'use strict';

const ESSERIALIZER_NULL = '__ESSERIALIZER_NULL__';

const ARRAY_FIELD = 'ess_arr';
const BOOLEAN_FIELD = 'ess_bool';
const CLASS_NAME_FIELD = 'ess_cn';
const OPTIONS_FIELD = 'ess_opt';
const TIMESTAMP_FIELD = 'ess_ts';
const TO_STRING_FIELD = 'ess_str';

const BUILTIN_CLASS_INT8ARRAY = 'Int8Array';
const BUILTIN_CLASS_UINT8ARRAY = 'Uint8Array';
const BUILTIN_CLASS_UINT8CLAMPEDARRAY = 'Uint8ClampedArray';
const BUILTIN_CLASS_INT16ARRAY = 'Int16Array';
const BUILTIN_CLASS_UINT16ARRAY = 'Uint16Array';
const BUILTIN_CLASS_INT32ARRAY = 'Int32Array';
const BUILTIN_CLASS_UINT32ARRAY = 'Uint32Array';
const BUILTIN_CLASS_FLOAT32ARRAY = 'Float32Array';
const BUILTIN_CLASS_FLOAT64ARRAY = 'Float64Array';
const BUILTIN_CLASS_BIGINT64ARRAY = 'BigInt64Array';
const BUILTIN_CLASS_BIGUINT64ARRAY = 'BigUint64Array';
const BUILTIN_CLASS_ARRAYBUFFER = 'ArrayBuffer';
const BUILTIN_CLASS_SHAREDARRAYBUFFER = 'SharedArrayBuffer';
const BUILTIN_CLASS_BOOLEAN = 'Boolean';
const BUILTIN_CLASS_DATAVIEW = 'DataView';
const BUILTIN_CLASS_DATE = 'Date';
const BUILTIN_CLASS_INTL_COLLATOR = 'Collator';
const BUILTIN_CLASS_INTL_DATETIMEFORMAT = 'DateTimeFormat';
const BUILTIN_CLASS_INTL_LISTFORMAT = 'ListFormat';
const BUILTIN_CLASS_INTL_LOCALE = 'Locale';
const BUILTIN_CLASS_INTL_NUMBERFORMAT = 'NumberFormat';
const BUILTIN_CLASS_INTL_PLURALRULES = 'PluralRules';
const BUILTIN_CLASS_INTL_RELATIVETIMEFORMAT = 'RelativeTimeFormat';
const BUILTIN_CLASS_REGEXP = 'RegExp';
const BUILTIN_CLASS_SET = 'Set';
const BUILTIN_CLASS_STRING = 'String';
const BUILTIN_CLASS_ERROR = 'Error';
const BUILTIN_CLASS_EVAL_ERROR = 'EvalError';
const BUILTIN_CLASS_RANGE_ERROR = 'RangeError';
const BUILTIN_CLASS_REFERENCE_ERROR = 'ReferenceError';
const BUILTIN_CLASS_SYNTAX_ERROR = 'SyntaxError';
const BUILTIN_CLASS_TYPE_ERROR = 'TypeError';
const BUILTIN_CLASS_URI_ERROR = 'URIError';
const BUILTIN_CLASS_AGGREGATE_ERROR = 'AggregateError';
const BUILTIN_TYPE_BIG_INT = 'BI';
const BUILTIN_TYPE_NOT_FINITE = 'NF';
const BUILTIN_TYPE_UNDEFINED = 'UD';

const ALL_BUILTIN_ARRAYS = [
  BUILTIN_CLASS_INT8ARRAY,
  BUILTIN_CLASS_UINT8ARRAY,
  BUILTIN_CLASS_UINT8CLAMPEDARRAY,
  BUILTIN_CLASS_INT16ARRAY,
  BUILTIN_CLASS_UINT16ARRAY,
  BUILTIN_CLASS_INT32ARRAY,
  BUILTIN_CLASS_UINT32ARRAY,
  BUILTIN_CLASS_FLOAT32ARRAY,
  BUILTIN_CLASS_FLOAT64ARRAY,
  BUILTIN_CLASS_BIGINT64ARRAY,
  BUILTIN_CLASS_BIGUINT64ARRAY
];

const ALL_BUILTIN_ERRORS = [
  BUILTIN_CLASS_ERROR,
  BUILTIN_CLASS_EVAL_ERROR,
  BUILTIN_CLASS_RANGE_ERROR,
  BUILTIN_CLASS_REFERENCE_ERROR,
  BUILTIN_CLASS_SYNTAX_ERROR,
  BUILTIN_CLASS_TYPE_ERROR,
  BUILTIN_CLASS_URI_ERROR,
  BUILTIN_CLASS_AGGREGATE_ERROR
];

const ALL_BUILTIN_INTLS = [
  BUILTIN_CLASS_INTL_COLLATOR,
  BUILTIN_CLASS_INTL_DATETIMEFORMAT,
  BUILTIN_CLASS_INTL_LISTFORMAT,
  BUILTIN_CLASS_INTL_NUMBERFORMAT,
  BUILTIN_CLASS_INTL_PLURALRULES,
  BUILTIN_CLASS_INTL_RELATIVETIMEFORMAT
];

const CLASSNAMES_WHOSE_ENUMERABLE_PROPERTIES_SHOULD_BE_IGNORED = [
  BUILTIN_CLASS_STRING, ...ALL_BUILTIN_ARRAYS
];

export {
  ESSERIALIZER_NULL,
  ALL_BUILTIN_ARRAYS,
  ALL_BUILTIN_ERRORS,
  ALL_BUILTIN_INTLS,
  CLASSNAMES_WHOSE_ENUMERABLE_PROPERTIES_SHOULD_BE_IGNORED,
  BUILTIN_CLASS_INT8ARRAY,
  BUILTIN_CLASS_UINT8ARRAY,
  BUILTIN_CLASS_UINT8CLAMPEDARRAY,
  BUILTIN_CLASS_INT16ARRAY,
  BUILTIN_CLASS_UINT16ARRAY,
  BUILTIN_CLASS_INT32ARRAY,
  BUILTIN_CLASS_UINT32ARRAY,
  BUILTIN_CLASS_FLOAT32ARRAY,
  BUILTIN_CLASS_FLOAT64ARRAY,
  BUILTIN_CLASS_BIGINT64ARRAY,
  BUILTIN_CLASS_BIGUINT64ARRAY,
  BUILTIN_CLASS_ARRAYBUFFER,
  BUILTIN_CLASS_SHAREDARRAYBUFFER,
  BUILTIN_CLASS_BOOLEAN,
  BUILTIN_CLASS_DATAVIEW,
  BUILTIN_CLASS_DATE,
  BUILTIN_CLASS_INTL_COLLATOR,
  BUILTIN_CLASS_INTL_DATETIMEFORMAT,
  BUILTIN_CLASS_INTL_LISTFORMAT,
  BUILTIN_CLASS_INTL_LOCALE,
  BUILTIN_CLASS_INTL_NUMBERFORMAT,
  BUILTIN_CLASS_INTL_PLURALRULES,
  BUILTIN_CLASS_INTL_RELATIVETIMEFORMAT,
  BUILTIN_CLASS_REGEXP,
  BUILTIN_CLASS_SET,
  BUILTIN_CLASS_STRING,
  BUILTIN_CLASS_ERROR,
  BUILTIN_CLASS_EVAL_ERROR,
  BUILTIN_CLASS_RANGE_ERROR,
  BUILTIN_CLASS_REFERENCE_ERROR,
  BUILTIN_CLASS_SYNTAX_ERROR,
  BUILTIN_CLASS_TYPE_ERROR,
  BUILTIN_CLASS_URI_ERROR,
  BUILTIN_CLASS_AGGREGATE_ERROR,
  BUILTIN_TYPE_BIG_INT,
  BUILTIN_TYPE_NOT_FINITE,
  BUILTIN_TYPE_UNDEFINED,
  ARRAY_FIELD,
  BOOLEAN_FIELD,
  CLASS_NAME_FIELD,
  OPTIONS_FIELD,
  TIMESTAMP_FIELD,
  TO_STRING_FIELD
};